name: Release

on:
  pull_request:
    types: [opened, synchronize]  # debug
    # branches:
      # - autoupdate


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install hub
      uses: geertvdc/setup-hub@master

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/workflows/tasks.py package

    - name: Update Release File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_REPO_NAME: ${{ github.repository }}
      run: python .github/workflows/tasks.py update_release_file
