name: Pre-review validation

on:
  repository_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - autoupdate

jobs:
  build:
    if: (github.event_name == 'repository_dispatch' && github.event.action == 'validation') ||
        (github.event_name == 'pull_request')
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Download tests
      run: curl https://raw.githubusercontent.com/FriendsOfGalaxy/galaxy-integrations-updater/master/tests.py --output ../tests.py

    - name: Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_REF: ${{ github.base_ref }}
      run: |
        pip install pytest
        pytest ../tests.py

